### ISSUE TITLE
Update Patient: RangeError [Error]: Invalid time value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#100]
## Describe the bug
See run failure with error `RangeError [Error]: Invalid time value`

I think something may be going on with date/time formatting in the source data... but we need to identify (1) is there an issue with the source data in state, or (2) with the OpenFn logic related to date/time. 

## To Reproduce
Feel free to re-run on prod: 
https://www.openfn.org/projects/miraclefeet/runs/061894ac-b4d9-7495-9300-9971aad10274

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

### adaptor
salesforce

### state.json
Credentials: See LP for `MiracleFeet Salesforce Production`
Message: https://www.openfn.org/projects/miraclefeet/messages/061894ac-9c6c-7673-8c22-8fdb80e1d9c4

## Expected behavior
Depending on what you find... we might either advise the client to clean the data, or modify the job to automate data cleaning... so keep me posted on your findings!

**Comment by aleksa-krolls** [comment]
@elias-ba lining up a couple more for Monday based on errors I'm seeing today :-)

**Comment by elias-ba** [comment]
Hello @aleksa-krolls this is failing because of the format of the date `"date_first_visit": "05-10-2021"` in the message that's not supported by the `dateConverter` function in the expression file. This `date_first_visit` is the only one in the message that has this *DD-MM-YYYY* format. All the other dates are in *YYYY-MM-DD* format which is supported by the `dateConverter` function. Should we update the `dateConverter` function to handle different date formats or should we tell the client to clean the data ?

**Comment by aleksa-krolls** [comment]
Thanks @elias-ba! Let me check with the client, but I think we'll probably ask them to clean the data. But I went ahead and noted the assumed format is `YYYY-MM-DD`.
