### ISSUE TITLE
Add_New_Visit: RangeError [Error]: Invalid time value

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#120]
## Describe the bug
See run failure with error `RangeError [Error]: Invalid time value`. Can you tell me what date format does it not like? (We might either update the job, or ask the client to update the data.)
https://www.openfn.org/projects/miraclefeet/runs/06201215-1d4c-79bf-a788-ea5005ebdd78

### expression.js
https://github.com/OpenFn/Miracle-Feet/blob/master/add_new_visit__UPDATED.js

### state.json
SEE LP: `MiracleFeet Salesforce Production`
https://www.openfn.org/projects/miraclefeet/messages/06201215-1452-7e33-9d77-ee6ede4760ce

**Comment by lakhassane** [comment]
@aleksa-krolls there were an issue with some recent add (from yesterday) about the function `dateConverter`. It's fixed now: https://www.openfn.org/projects/miraclefeet/runs/062023dc-9b40-7680-9e8e-891e7df64687.

Instead of giving a path to a date, it was given `state` directly. So the data is fine in my opinion.
