### ISSUE TITLE
Only schedule SMS-s within a specified time window

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#52]
## Background, context, and business value

See #32 for latest version of original specs.

## The specific request, in as few words as possible

We sometimes scheduled messages to be sent out during the night based on the incoming CommCare form submission times. We want to make sure that we only schedule SMS-s from 8am to 8pm local time in each time zone.

**Check when, in local time, a message would be sent. If this would be between 8pm and 8am local time, then schedule the SMS for 8am.**

## state.json

For Infobip login see `LP Infobip Portal (MiracleFeet)`.

## adaptor

`language-http`

## expression.js

Update job `schedule_sms.js`

### side effects

For example if an SMS would be scheduled for 2.05am local time, it should be scheduled for 8am local time.
For example if an SMS should be scheduled immediately and it's now 9.05am local time, it should be scheduled for now.

**Comment by ritazagoni** [comment]
@lakhassane Before digging into implementation could you give us an estimate for this?

**Comment by lakhassane** [comment]
@ritazagoni should we always schedule at 8am if the local sending time is out of the range 8am-8pm?

**Comment by ritazagoni** [comment]
@lakhassane I wasn't specific enough: if, in local time a message would be sent between 8pm and 8am, use 8am as [schedule start date](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=606433e3#gid=179313688&range=F:F) for that message

**Comment by ritazagoni** [comment]
If the estimate for implementing this is less than 4 hours, please go ahead with it.

**Comment by lakhassane** [comment]
@ritazagoni it's good for testing

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni and I are finding that if, for example, we receive a CommCare form in the afternoon... we're trying to scheduling the message for a time earlier that day... rather than 9am the next day. 

See run here for a registration form that we received on `2021-05-12T09:54:55.787Z` ... this is after 9am... but we're scheduling the message to send at a time in the past `2021-05-12T09:00:00`. 
https://www.openfn.org/projects/pdbznd/runs/r9wxmj7p

Instead, when we schedule Registration messages... we want to (1) check if the current time is after 9am GMT, and (2) if yes, schedule for next day (rather than 9am on the same day). 

To test, here is a state received on today that you can re-run: https://www.openfn.org/projects/pdbznd/messages/mdbgqjb5

**Comment by lakhassane** [comment]
@aleksa-krolls @ritazagoni this might trigger another. Because if we decide to move the sms of today for tomorrow (june 15) at 9am, we might probably already had sms scheduled that day 15 for the same hour. Which is messing up with the schedule date of all sms's

**Comment by lakhassane** [comment]
@ritazagoni @aleksa-krolls so I made the change as we were supposed to. Feel free to re-run and check new logs

**Comment by ritazagoni** [comment]
hey @lakhassane we've decided to change the Schedule Start Date of some of the messages. Please find the updated SSD-s [here](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=606433e3&pli=1#gid=262234774) (I have highlighted the changes in this [sheet](https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit?ts=606433e3&pli=1#gid=1102507477))

**Comment by lakhassane** [comment]
@ritazagoni I update the mapping object accordingly.
