### ISSUE TITLE
If a run fails because of an empty field, let's log the field name

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#65]
## Describe the bug
When a run fails due to an empty field in state, we log the error `Cannot read property 'map' of undefined`.  Let's log the field that we were expecting to have a value and caused the run to fail.
Fields to check:
`form.calcs.sms.time_zone`

If time_zone is undefined OR null, then throw an error and log the message: `SMS automation failed because the field time_zone is missing from the CommCare form`.

## To Reproduce
This [run](https://www.openfn.org/projects/pdbznd/runs/r44jrz9n) on [message ](https://www.openfn.org/projects/pdbznd/messages/m957pz5z) failed because `time_zone` had no value. 

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json
See `LP` for Infobip portal

## Expected behavior
Log field name where value was missing.

## To test/resolve
1. After the desired output is working locally (from the CLI), please push commits to master
2. Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/pdbznd/runs/rk53jb7n) and confirming success.

**Comment by aleksa-krolls** [comment]
@ritazagoni It is going to be a lot of work for Mamadou to check _any_ field... so I think we need to be specific about which fields to check for before running the job. For example, we can change this issue to be like...
If `time_zone`, `language_code`, or `X` are undefined OR null, then throw an error and log the Message `SMS automation failed because the field `{X}` is missing from the CommCare form.

Please list which other fields to check to make the request more specific, and feel free to add to the bottom of the backlog.

**Comment by ritazagoni** [comment]
Thanks! Updated and added to backlog.

**Comment by lakhassane** [comment]
Hey @ritazagoni for this one I think the failure is not due to timezone (no timezone would just send the sms right away without applying an offset) but it's because of `language_code`.
The message has `en` for code while previous specs was using `English`

**Comment by ritazagoni** [comment]
Ah thanks for that @lakhassane . It was because our first option to use, `sms_language`, is empty. I've removed `language_code` altogether because it's in the wrong format and kept `English` as the fallback option.
