### ISSUE TITLE
"Invalid time value" error

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#66]
## Describe the bug
This [run](https://www.openfn.org/projects/pdbznd/runs/ryapm3kj) on [this](https://www.openfn.org/projects/pdbznd/messages/mmqnbg8w) message failed with the error: `RangeError [Error]: Invalid time value`. 
[Here's](https://www.openfn.org/projects/pdbznd/runs/rg5gya48) another example for the same error message.

Time zone is correctly filled and I haven't found any non-standard date or time values in the message.

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js

### state.json

See `LP` for `Infobip` portal

## To test/resolve
1. After the desired output is working locally (from the CLI), please push commits to master.
2. Please test the change on OpenFn.org by re-running [this run](https://www.openfn.org/projects/pdbznd/runs/ryapm3kj) and confirming success.

**Comment by lakhassane** [comment]
@ritazagoni the timezone was set in state but was not in the mapping object in the job then returning `undefined`.
We have `"time_zone": "Asia/Manila"`, however I don't recall seeing the time value for this zone in the specs. Can you add it whenever available at line https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js#L78

I made a check to not map the timezone when undefined so the job should still run ok.

**Comment by aleksa-krolls** [comment]
@ritazagoni make sure to reprocess failed SMSs!

**Comment by ritazagoni** [comment]
thanks both.

**Comment by lakhassane** [comment]
Hey @ritazagoni we might be seeing this because we have two paths given for next_visit_date when we need to schedule `visitAfter` ==> ` form.calcs.general.next_visit_date`  and `form.calcs.next_visit_date.next_visit_date`

The first one doest not exist in the state, and the second one is empty. I assume the same thing happened for the second failing run.

<img width="393" alt="Screen Shot 2021-07-14 at 14 05 44" src="https://user-images.githubusercontent.com/8411231/125635889-d8bc7c16-99af-445f-8008-f48947eb3f2b.png">

**Comment by aleksa-krolls** [comment]
From the client @ritazagoni to spec next week...
If `next_visit_date` is blank, we will only NOT send visit reminders (because there is no upcoming visit - treatment is complete).
