### ISSUE TITLE
Add a list of usernames to schedule_sms job 

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#72]
## Background, context, and business value

Currently in schedule_sms.js we only run the scheduling logic if `username` in state matches certain criteria. Going forward, we would like to add a list of `username`-s to this condition. 

For example, in pseudocode:
```
const usernameList = [username1, username2, username3]
if (username.includes('test') || username.includes('practica') ||  usernameList  contains username {
...
}
```
Please add this logic to the job in a way where it is easy to add new usernames to the list.

## adaptor

`language-http`

## expression.js

update [schedule_sms.js](https://github.com/OpenFn/Miracle-Feet/blob/65a2557fa0aafa343c55a337036664bd39db1186/schedule_sms.js#L199-L200)

**Comment by lakhassane** [comment]
@ritazagoni I have added a `allowedUsernames` array where you can add more usernames.

https://github.com/OpenFn/Miracle-Feet/blob/master/schedule_sms.js#L184

**Comment by aleksa-krolls** [comment]
@ritazagoni Mamadou (rightly) implemented this change as you spec'd it... but we should have told him the integration was live, because `test` SMSs were being processed and failing. See example here: https://www.openfn.org/projects/pdbznd/runs/rrkpmwxw

I updated the job so it is only referencing the 1 username again, but we need to be really careful with change management now that this solution is live! Let's discuss more on Monday :)
