### ISSUE TITLE
Field on Salesforce `Contact` only updated when job re-run

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#92]
## Describe the bug
The `  Duplicate_Patient__c: true` value we're sending is not being updated on the Contact in SF when the [Update Patient](https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js) job initially runs, even if the run shows success. 

However, when it is later re-run manually the Contact is updated as originally expected. 

## To Reproduce
Example 1: Update didn't work: https://openfn.org/projects/miraclefeet/runs/06140823-2000-71fd-aa6f-a56c97a70b6a
Update didn't work https://openfn.org/projects/miraclefeet/runs/06140823-5000-7e27-9169-f36f264a932f

Re-run worked : https://openfn.org/projects/miraclefeet/runs/0618e25f-8037-78b6-834d-364caf343a85

Example 2: Update didn't work: https://openfn.org/projects/miraclefeet/runs/061601d2-59e9-7c75-80d5-3c4ba4312e9d
Update didn't work: https://openfn.org/projects/miraclefeet/runs/061601d3-2b0e-7d85-bd87-50aa7bd5027c
Re-run worked: https://openfn.org/projects/miraclefeet/runs/0618e26b-a8e3-7ce4-814d-5a52bad0b5b6

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/Miracle-Feet/blob/master/update_patient_UPDATED.js

### state.json

See LP `MiracleFeet Salesforce Production`
Sample state: https://github.com/OpenFn/Miracle-Feet/blob/master/sample_data/update_patient_duplicate.json

**Comment by aleksa-krolls** [comment]
@ritazagoni I've been checking this out, and the job looks fine... but it does look like these jobs are on a very old salesforce adaptor version. I think we should...
1. upgrade the jobs to the latest `v2.7.2` (@lakhassane pls confirm this is the best version)
2. Test syncing this data to sandbox to see if when we run this... does it successfully update the SF record _in the first run_? 

To support testing in step 2... in sandbox, we might want to first make sure we've created a Patient record with the same uuid (so that this record already exists in sandbox). And then try syncing this Message to the sandbox to validate whether the first-time sync works and correctly updates the record. 

Happy to help with this tomorrow as needed, but hopefully straightforward. If still not working when we sync to sandbox, I think we can then loop in Mamadou to take a look and play around w/ the sandbox record.

**Comment by aleksa-krolls** [comment]
@ritazagoni let me know if you want to talk this through again later today/ keep me posted on how testing goes

**Comment by ritazagoni** [comment]
note from Mamadou: v2.7.2 is the version to use

**Comment by aleksa-krolls** [comment]
Seems to be related to SF-side automation, not an OpenFn issue. Closing for now.
