### ISSUE TITLE
Log inactive clinics fetched

### ISSUE THREAD

**Issue by ritazagoni** [OpenFn/Miracle-Feet#94]
## Background, context, and business value

Currently in [getInactiveClinics.js](https://github.com/OpenFn/Miracle-Feet/blob/master/getInactiveClinics.js) we only log Contacts that belong to inactive accounts. See https://github.com/OpenFn/Miracle-Feet/issues/80 for original request.

## The specific request, in as few words as possible

After both queries ([1](https://github.com/OpenFn/Miracle-Feet/blob/ba3fee82520b152b61d53504da477b8efa979020/getInactiveClinics.js#L1-L3) and [2](https://github.com/OpenFn/Miracle-Feet/blob/ba3fee82520b152b61d53504da477b8efa979020/getInactiveClinics.js#L12-L14)) let's log all `Account`-s and `Account.Status`-s we fetched.

## state.json
See LP for `MiracleFeet SMS Sandbox Salesforce` (contact AK to get verification) 
and `Infobip Portal (MiracleFeet)`

## adaptor
`language-salesforce`
`language-http`

**Comment by lakhassane** [comment]
Rita I added some logs for the all the inactive clinics from the 2 queries.

<img width="470" alt="Screen Shot 2021-11-22 at 11 58 56" src="https://user-images.githubusercontent.com/8411231/142857993-8a24060d-caec-4169-88b2-15db51fafc1f.png">

**Comment by aleksa-krolls** [comment]
@lakhassane It looks like this logging is now throwing some TypeErrors... can you please take a look and re-run? 
https://www.openfn.org/projects/miraclefeet/runs/061a74ff-7670-7fbc-ae84-426d22f50333

@ritazagoni Beth's testing for deactivating clinics failed because of this. Logging results here: 
https://docs.google.com/spreadsheets/d/1quhQJgQkVRC8oObDzkwgnnm-Rov5BGOW85I4YqcNV0I/edit#gid=959470187

**Comment by lakhassane** [comment]
@aleksa-krolls it's tested here. We needed to ensure `Account` existed before logging `Name` and `Status__c`
